#!/bin/bash
SERVICE="stalonetray"
if pgrep -x "$SERVICE" >/dev/null
then
    killall stalonetray
else
    stalonetray &
    # uncomment to start nginx if stopped
    # systemctl start nginx
    # mail  
fi
