-- main options
vim.opt.formatoptions = vim.opt.formatoptions - [[c]] - [[r]] - [[o]]
vim.opt.iskeyword:append [[-]]
vim.opt.shortmess = [[IcF]]
vim.opt.hidden = true
vim.opt.wrap = false
vim.opt.whichwrap:append [[<,>,[,],h,l]]
vim.opt.encoding = [[utf-8]]
vim.opt.pumheight = 10
vim.opt.fileencoding = [[utf-8]]
vim.opt.cmdheight = 2
vim.opt.mouse = [[a]]
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.conceallevel = 0
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.smarttab = true
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.laststatus = 2
vim.opt.showtabline = 2
vim.opt.number = true
vim.opt.background = [[dark]]
vim.opt.showmode = false
vim.opt.showcmd = false
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.updatetime = 300
vim.opt.signcolumn = [[yes]]
vim.opt.timeoutlen = 100
vim.opt.clipboard = [[unnamedplus]]
vim.opt.incsearch = true
vim.opt.guifont = [[monospace]]
vim.opt.ruler = false
vim.opt.cursorline = true
vim.opt.completeopt = [[menu]],[[menuone]],[[noselect]]
vim.opt.omnifunc = [[syntaxcomplete#Complete]]
vim.cmd([[filetype plugin on]])
