#!/bin/sh
# Xsetup - run as root before the login dialog appears

xrandr --setprovideroutputsource intel nvidia

OUTPUT=$(bash /home/shino/.config/xrandr_displays.sh)
echo "${OUTPUT}" > /home/shino/xsetup_test2

xrandr ${OUTPUT}
